### ISSUE TITLE
Setting a default font color

### ISSUE THREAD

**Issue by wasamasa** [mobius3/KiWi#16]
I'm currently trying out a darker design and would like to have a light font color for that, however I only found `KW_SetLabelColor` for setting label font colors.  This would solve it for me, but doesn't cover other widgets (like editbox or button) and is more bothersome than setting a global default like one can already do with the font (see `KW_SetFont`).

**Comment by mobius3** [comment]
I see your point. Well, maybe we can do it like the font, but I'm thinking on how would we check if the user has set the color on the label or not. `KW_GetLabelFont()` checks if the widget has a font, if not, it returns `KW_GetFont()`.

I'll think more on this problem later, thanks for bringing it up.

**Comment by wasamasa** [comment]
Wouldn't that just be the matter of having a nullable color struct item for widgets and checking whether it's null (not set, use global value) or not null (set, use local value)?

**Comment by mobius3** [comment]
Well, sort of. I was not willing to use dynamic memory for this, so I cannot have a nullable field and any value that you can assign in a color struct is a valid color.

```
struct KW_color {
  char r, g, b, a;
}
```

There isn't a value that I can use to tell if this was set or not. Maybe a field, `set`, to tell if it was set or not.

**Comment by wasamasa** [comment]
Ah, makes sense.

**Comment by mobius3** [comment]
I've implemented a set of functions for setting text color in the gui, editbox, label and buttons. The widgets will use the text color defined in the gui if not set on them.

**Comment by wasamasa** [comment]
Thanks, that will do.

**Comment by wasamasa** [comment]
I do wonder though, why is it `GetTextColor` / `SetTextColor` / `WasTextColorSet` for widgets as opposed to `GetFontColor` and `SetFontColor` for the GUI?

**Comment by leo-freitas** [comment]
Ah. Thats becaue i renamed the widget functions after i wrote them. Thanks for catching that.
