### ISSUE TITLE
CHICKEN Scheme binding

### ISSUE THREAD

**Issue by wasamasa** [mobius3/KiWi#21]
This will be my probably last issue for now.  I've published [the code](https://github.com/wasamasa/kiwi), released [an egg](http://wiki.call-cc.org/eggref/4/kiwi) and made [an announcement](http://emacsninja.com/posts/kiwi.html).  Feel free to include links to these in the README.  Thanks for your help so far, I've had lots of fun working with your library :D

**Comment by mobius3** [comment]
Thank you very much for all your help! Great job, specially on the documentation part, which is usually the hardest for programmers. I'm really happy that someone else (other than myself :) could understand KiWi enough to make a binding for it. I'll keep working on the issues you opened, thanks for them and for the Arch build script.

Good luck!

BTW, I wonder if it wouldn't be a good idea to reference a specific KiWi commit in your egg dependencies, considering the library is not done and the API might break in the future.

**Comment by wasamasa** [comment]
The foreign-depends thing is an informal hint what one would need to compile the egg successfully.  I suspect more people would be reading the wiki docs, so I'll put a date and commit there.
