### ISSUE TITLE
resource.c missing for successful Cmake?

### ISSUE THREAD

**Issue by Burnrate** [mobius3/KiWi#29]
This is probably more due to my lack of cmake understanding but I can't get it to generate successfully.

```
CMake Error at src/CMakeLists.txt:51 (add_library):
  Cannot find source file:

    resources.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: KiWi
CMake Error in src/CMakeLists.txt:
  Exporting the target "KiWi" is not allowed since its linker language cannot
  be determined
```

Any info on what is happening here?  Is it just me?  Can you provide a successful cmake configuration as an example, pretty please?  :)

**Comment by mobius3** [comment]
Hoi. Sorry for the late response. Can you tell me which CMake version you're using? Also, are you on windows or linux? which distro/version?

Meanwhile, I'll look at it.

Thanks for your report!

**Comment by mobius3** [comment]
Does this error happens when you try compiling KiWi or using KiWi in another project (as in `include_directory(third_party/KiWi)`)?

The file `resources.c` is generated by the file `resources/kiwires.cmake`. `kiwires.cmake` compiles a program called `file2c` from source `src/file2c.c`. This program is then executed to generate `resources.c`. All of this is generated during the configure step (`cmake path/to/KiWi`). If you're using KiWi inside another project that my be the reason, which would be my fault because I'm lazy and I didn't test it properly :)

Can you check if `resources.c` is generated somewhere in your `build` directory? If so, can you tell-me where?

**Comment by krystcich** [comment]
Hello!
Here's what worked for me:
1. comment line #6 in KiWi-master/resources/cmake
2. compile only file2c.c by hand (gcc file2c.c -o file2c.exe) and move file2c.exe file to KiWi-master/build
3. link libraries for CMake in correct order mingw32;SDL2main;SDL2;SDL2_image;SDL2_ttf (make sure other SDL2 related stuff is pointing the right directories) 
4. Configure, Generate (CMake: 3.11.0-rc3 on Windows with MinGW Makefile option) now goes fine
5. change utf8.c line #21 to: #elif !defined(__OpenBSD__)
6. go to KiWi-master/build/examples/drag, run cmd, make
7. copy libKiWi.dll from KiWi-master/build/src to KiWi-build/examples/drag/
8. add all usual SDL2 dll files (SDL2.dll, SDL2_image.dll, SDL2_ttf.dll, libpng16-16.dll, libfreetype-6.dll, zlib1.dll)
9. run drag.exe

Hope that helps somehow!

**Comment by Burnrate** [comment]
I'm using CMake 3.10.2 on Windows 10.

I've only tried to compile it by itself.  The resources.c file doesn't show up anywhere.  The configuration does complete and part of the generate, lots of partial project files in the demos and such.

**Comment by krystcich** [comment]
The resources.c error during Generate will go away after you compile file2c.c to file2c.exe, put the exe in a KiWi-master/build folder and try Generate again. Use this command while in KiWi-master/src: `gcc file2c.c -o file2c.exe`. 

I just tried again all my steps from my previous answer - it works for me.
Good luck!

**Comment by mobius3** [comment]
That is good to know. I'll boot Windows today and I'll try to provide a proper fix.

**Comment by krystcich** [comment]
Great :) While you're at it... Would it be a problem for you to add a shared object library to the CMake build? I'm trying to make KiWi work with Android and can't link it otherwise. Is there anything I should change before building for mobile, did you try it on Android? 

Will be gratefull for any heads-up!

**Comment by mobius3** [comment]
@krystcich well I have tested it with Android previously and it worked. It wasn't through CMake though. There is an `Android.mk` makefile on [KiWi's source root](https://github.com/mobius3/KiWi/blob/master/Android.mk) that I used to build it in the past but I'll admit that I havent tested it nowadays. It builds a static library as well  (and statically links to SDL), you can use it to link to your main `.so`, depending on your project's root `Android.mk`. SDL2 sources has an [android example](http://hg.libsdl.org/SDL/file/331397505b6c/android-project) that I used as a base and edited to build one of the examples and link with KiWi. I'd say thats the path to go. Let me know if you succeed and how (I'd only ask you to open another issue regarding this).

Building a shared library out of KiWi seems to not hurt anyone so I'll make it happen.

**Comment by Burnrate** [comment]
I was able to compile the file2.c as krystcich suggested and corrected the typo in utf8.c.  I haven't been able to run anything yet though.

Here are the errors from drag if it helps:
```
1>------ Build started: Project: KiWi, Configuration: Debug Win32 ------
1>   Creating library C:/Games/KiwiSDL/KiWi/build/src/Debug/KiWi.lib and object C:/Games/KiwiSDL/KiWi/build/src/Debug/KiWi.exp
1>KW_widget.obj : error LNK2019: unresolved external symbol _sprintf referenced in function _DrawDebugGizmos
1>C:\Games\KiwiSDL\KiWi\build\src\Debug\KiWi.dll : fatal error LNK1120: 1 unresolved externals
1>Done building project "KiWi.vcxproj" -- FAILED.
2>------ Build started: Project: drag, Configuration: Debug Win32 ------
2>drag.obj : error LNK2019: unresolved external symbol _printf referenced in function _DragStart
2>C:\Games\KiwiSDL\KiWi\build\examples\drag\Debug\drag.exe : fatal error LNK1120: 1 unresolved externals
2>Done building project "drag.vcxproj" -- FAILED.
3>------ Build started: Project: INSTALL, Configuration: Debug Win32 ------
3>-- Install configuration: "Debug"
========== Build: 1 succeeded, 2 failed, 2 up-to-date, 0 skipped ==========
```
I haven't done anything past that for the moment, so little time.  Thank you for your help

**Comment by krystcich** [comment]
@Burnrate sorry, won't be able to help with visual c++ :( Are steps 1-5 going fine for you? If you want to try it with just CMake, MinGW and make you can catch me on discord tommorow (I think I saw you on SDL2 channel) and I'll try to walk you through. Or wait for mobius3 input.


PS: @mobius3 I got a label working on android! Got reeeally tangled up in source files for a while because of the app crashing, but it seems I was just lacking files in assets folder. Sorry for polluting comments, but no issues to report so far :) (will keep you updated if anything goes wrong along the way, thanks!)

**Comment by mobius3** [comment]
@krystcich I'm glad it worked!

@Burnrate the fix for VS will take longer cause I'll have to download it all and my internet connection is rather slow. From what I gather of your logs, if you comment the lines having `sprintf` in KiWi it should build ok for now. I'll look into that as well.

**Comment by mobius3** [comment]
@krystcich I couldn't reproduce the problem in my setup. I used TDM-GCC 64. Which version of MinGW are you using? can you please post the output of the command `gcc -v`?

**Comment by Burnrate** [comment]
Yay
[https://i.imgur.com/pRsc3HG.png](https://i.imgur.com/pRsc3HG.png)

It was a simple as hoped.  I commented out a couple of printf's also and finally setup the project correctly with all the references and got it running :)

**Comment by mobius3** [comment]
@Burnrate great! I assume that VS has excluded sprintf from their libc... I'll find an alternative.

**Comment by Burnrate** [comment]
@mobius3 Also, remember, super fun things such as: VS does not output to console when debugging a windowed application so if you want to make available debugging information ...
(don't forget printf also)
(I'm so sorry)

**Comment by mobius3** [comment]
@Burnrate true enough. I'll take the blame, I didn't tested it enough on VS :) thanks for reporting and helping.

**Comment by krystcich** [comment]
@mobius3 sure, here's the output. 
If you need me to test with 7.3.0 or any other version, just let me know.
```
C:\>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=<my mingw path>/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/7.2.0/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../src/configure --enable-languages=c,c++ --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --disable-multilib -
-prefix=/c/temp/gcc/dest --with-sysroot=/c/temp/gcc/dest --disable-libstdcxx-pch --disable-libstdcxx-verbose --disable-nls --disable-shared --disable-win32-regi
stry --with-tune=haswell --enable-threads=posix --enable-libgomp
Thread model: posix
gcc version 7.2.0 (GCC)

```
After Configure going ok I get the error below (just checked again with a fresh .zip to make sure I'm sane ;P) 

```
CMake Error at src/CMakeLists.txt:51 (add_library):
  Cannot find source file:

    <my correct KiWi path>/KiWi-master/build/src/resources.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at src/CMakeLists.txt:51 (add_library):
  No SOURCES given to target: KiWi
```
then after compiling file2c myself, the error goes away, it Generates fine and I can do make on the examples.

**Comment by mobius3** [comment]
@krystcich I see. I've tested with gcc 5.2.0, I will try with 7.2.0 and see what gives. If you can test it with 5.2.0 meanwhile it would help me a lot.

**Comment by krystcich** [comment]
I checked this morning on a different pc: fresh installs of CMake 3.9.6, TDM GCC 64 with GCC 5.1.0, fresh downloads of dev packages for SDL2, SDL_image and SDL_ttf (all paths pointed to .../x86_64-w64-mingw32/...)  – same error from CMake's Configure:
```
CMake Error at resources/kiwires.cmake:6 (try_compile):
  Cannot copy output executable

    '<proper path>/KiWi-master/build/CMakeFiles/CMakeTmp/cmTC_1faee.exe'

  to destination specified by COPY_FILE:

    'file2c.exe'

Call Stack (most recent call first):
  src/CMakeLists.txt:49 (kiwires)
```
(again, after doing gcc file2c.c -o file2c.exe by hand and placing in build it goes fine through Configure and Generate)
Couldn't find 5.2, but I hope it helps somehow anyway.

**Comment by krystcich** [comment]
I deleted the comment to further investigate before bothering you, but it got to you anyway. 

I was having that same error previously, that's probbably why I ignored the difference, sorry for the confusion. To verify I just tested it on my CMake 3.11/GCC 7.2.0 with an old .zip (25 Jan commit 471425c) and an up to date one. After linkning SDL stuff, the Configure is producing that error in both:
```
CMake Error at resources/kiwires.cmake:6 (try_compile):
  Cannot copy output executable

    '<clean path, no special characters, no spaces >/KiWi-master/build/CMakeFiles/CMakeTmp/cmTC_13627.exe'

  to destination specified by COPY_FILE:

    'file2c.exe'

Call Stack (most recent call first):
  src/CMakeLists.txt:49 (kiwires)
```
...but the good news is: it goes away for me after running CMake as administrator (so you're right about permissions I think - I forgot about doing it differently at some point). Nevertheless I still can't Generate both of them with that error on line 51:
```
CMake Error at src/CMakeLists.txt:51 (add_library):
  Cannot find source file:

    resources.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at src/CMakeLists.txt:51 (add_library):
  No SOURCES given to target: KiWi
```
I also tried installing TDM-GCC-64  5.1 - same result (don't have access to CMake 3.9.6 now, but can check next week if you think it helps somehow).

**Comment by mobius3** [comment]
Do you mind searching for this file on your disk to see if it ended up somewhere else?

**Comment by krystcich** [comment]
Not at all. I started all clean to be sure - after the error file2c.exe actually sits inside of C:\Program Files\CMake\bin. No trace of resources.c

**Comment by mobius3** [comment]
I see. That's the problem right there. I just made a commit that might fix the issue. In short, the `COPY_FILE` argument from cmake's `try_compile` command copies the file to the working directory that the `cmake.exe` is being run on if no path is specified. In both your cases  that seems to bee cmake's install directory.

Can you please try again and see if the problem goes away (@Burnrate and @krystcich)? You should'nt need to use cmake as admin anymore.

**Comment by krystcich** [comment]
I confirm - the problem is gone :)

**Comment by Burnrate** [comment]
@mobius3 
I deleted the whole thing and cloned and set it up again.  Almost the same exact error.  This time it just includes the whole path of where it thinks it will find resources.c

```
CMake Error at src/CMakeLists.txt:51 (add_library):
  Cannot find source file:

    C:/Games/KiwiSDL/KiWi/build/src/resources.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
```
resources.c still doesn't appear anywhere else either.

**Comment by mobius3** [comment]
Alright. I'll look into it. Can you tell me which version of Visual Studio are you using? Also, can you lookup the file `file2c.exe` to see if it is somewhere else in your computer?

**Comment by Burnrate** [comment]
Using VS 2017 (version 15) MSVC 19.13.26128.0.

No file2c.exe anywhere.

I updated my cmake to 3.11.0 also and same thing.  I'm doing everything x86.

**Comment by mobius3** [comment]
Ok, thanks. I managed to reproduce it with VS 2017 as well.

**Comment by mobius3** [comment]
@Burnrate I believe I fixed it. file2c.c uses VLA from C99 which VC++ doesn't support yet. I used dynamic memory instead. Can you try again with the newest commit, please?

**Comment by mobius3** [comment]
Right. `make_identifier` is buggy still. hold on.

**Comment by mobius3** [comment]
Ok, @Burnrate, I believe I fixed it. Can you test please?

**Comment by Burnrate** [comment]
@mobius3 

It configured and ran without a problem but no lib's or dll's were made.  I ran cmake with debug output and it gave me this.

```
 Entering             C:/Games/KiwiSDL/KiWi/src
CMake Warning (dev) at resources/kiwires.cmake:6 (try_compile):
  Policy CMP0066 is not set: Honor per-config flags in try_compile()
  source-file signature.  Run "cmake --help-policy CMP0066" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  For compatibility with older versions of CMake, try_compile is not honoring
  caller config-specific compiler flags (e.g.  CMAKE_C_FLAGS_DEBUG) in the
  test project.
Call Stack (most recent call first):
  src/CMakeLists.txt:49 (kiwires)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by mobius3** [comment]
That is just a warning, I don't think its a problem. I'll look into it, though.

Does VS says anything of interest when you build the resulting solution there?

**Comment by Burnrate** [comment]
I must have messed up something in VS last night.  I think the folder I was looking in wasn't refreshed and showing the .dll either.

I started again from the beginning and had it all work.  :)

Thank you for all the help!

**Comment by mobius3** [comment]
Awesome! Thank you both for your patience and willingness to help!
