### ISSUE TITLE
Is editbox example wrong?

### ISSUE THREAD

**Issue by aferust** [mobius3/KiWi#36]
I am creating a binding for dlang. It took sometime to figure out how to run editbox example. KW_CreateEditbox function returns a KW_Widget* handle. But in the example, there is no something like  KW_Widget* eBox = KW_CreateEditbox(.....). To run the example in d, I had to do like:
KW_Widget * e_box;

void OKClicked(KW_Widget * widget, int b){
    const(char*) text = KW_GetEditboxText(e_box);
    printf(text);
}
in main:
e_box = KW_CreateEditbox(gui, frame, "Edit me!", &editboxrect);
  ...
  KW_OnMouseDown cb = cast(KW_OnMouseDown)(&OKClicked);
  KW_AddWidgetMouseDownHandler(okbutton, cb);

**Comment by aferust** [comment]
Anyway, it is working now [here](https://github.com/aferust/dkiwi): https://github.com/aferust/dkiwi

**Comment by mobius3** [comment]
You are probably right! Also, thank you for your D binding! I'm a little short of time right now, if you could be so kind and provide a pull request fixing the example I'll gladly accept it.

**Comment by aferust** [comment]
Done!
