### ISSUE TITLE
missing implementations

### ISSUE THREAD

**Issue by aferust** [mobius3/KiWi#39]
Where are the implementations of those declarations?

void KW_AddGUITextColorChangedHandler(KW_GUI * gui, KW_OnGUITextColorChanged handler, void * priv);

void KW_RemoveGUITextColorChangedHandler(KW_GUI * gui, KW_OnGUITextColorChanged handler, void * priv);

**Comment by mobius3** [comment]
They were in with the wrong name. It is fixed now, thanks for your issue!
