### ISSUE TITLE
Text Block and Wrapping

### ISSUE THREAD

**Issue by Emersont1** [mobius3/kiwi#43]
Hi, i'm looking to change over to `TTF_RenderText_Blended_Wrapped` for multi line text rendering in preparation for an Editbox and a scrolling box of text for longer messages. However, this will mean an additional argument of width to be passed. I'm not sure what your opinion on introducing breaking changes into the library is so should i implement it as a new `RenderTextWrapped` function, or just extend the existing function and any uses within the library, and set it to not wrap if the width is set to 0

**Comment by mobius3** [comment]
I think we can handle this with an editbox option - `KW_EnableEditboxWrapping` and `KW_DisableEditboxWrapping`, which would set a flag on the `KW_Editbox` structure (this flag should be added to the end of the struct). `RenderEditboxText()` should then check if this flag is set and render accordingly. This would guarantee that the API doesn't break with current code.

If code gets too messy and too different (I didn't checked all the code paths for this), then I believe creating another component entirely would probably be better, albeit it's a lot more work and probably would involve a lot  of duplicated code.

Hey, thanks for your effort!
