### ISSUE TITLE
Distorted Icons

### ISSUE THREAD

**Issue by Emersont1** [mobius3/kiwi#48]
I'm not entirely sure of the purpose of lines 98-106 in `KW_label_internal.c`

using this example code, and the default (i think) skin:
```cpp
  KW_Widget * label;
  KW_Rect iconrect = { .x = 0, .y = 48, .w = 24, .h = 24 };
  for(int i =0;i<10;i++){
    label = KW_CreateLabel(gui, frame, "Label with an icon :)", &r);
    KW_SetLabelAlignment(label, KW_LABEL_ALIGN_LEFT, 0, KW_LABEL_ALIGN_TOP, 0);
    KW_SetLabelIcon(label, &iconrect);
    r.y+=50;
  }
```
## With the lines in place (distorted)
![screenshot1589056992](https://user-images.githubusercontent.com/23140112/81484579-6fd3ca80-923e-11ea-91d4-43a009bed4b2.png)

## With the lines in commented out (fine)
![screenshot1589057012](https://user-images.githubusercontent.com/23140112/81484580-6fd3ca80-923e-11ea-9bdb-310cb9e82435.png)

## Skin Image
![skin](https://user-images.githubusercontent.com/23140112/81484637-01dbd300-923f-11ea-8c74-8f9e86b357ea.png)

**Comment by mobius3** [comment]
I'm not sure as well, it does not seem to make any sense. Should've left a comment there of what I meant. Thanks for catching that.
