### ISSUE TITLE
Please don't print errors to stderr

### ISSUE THREAD

**Issue by wasamasa** [mobius3/KiWi#6]
See `KW_renderdriver_sdl2.c` for examples.  This is pretty icky as I'm currently writing a CHICKEN binding for KiWi and printing to stderr does interfere with CHICKEN's error reporting mechanism (throwing exceptions) and makes it impossible to do any better as there's no way of retrieving the error message.

**Comment by mobius3** [comment]
I'm printing to stdout now, but I was not sure if this fixes your problem. Maybe we can use the SDL_SetError, if printing to stdout is a problem to you.

**Comment by wasamasa** [comment]
I consider it an error if a library prints messages.

There are a number of mechanisms to signal errors, what I've come across so far were using a different return code and a function to retrieve the error message, changing a passed reference (useful when one cannot use the status code or for out-of-band reporting) and having an error callback argument.

The first would suffice as asking SDL for the error is apparently enough. What would need updating though would be the existing documentation to point out what can error out under which conditions.

**Comment by wasamasa** [comment]
Same applies to the instances of `SDL_LOG` in `KW_ProcessEvents`.  I expect any logging to only happen if I explicitly enable it, not for things like typing letters into an editbox.

**Comment by mobius3** [comment]
That was a debug leftover, you're right.

Em qui, 19 de mai de 2016 às 10:27, Vasilij Schneidermann <
notifications@github.com> escreveu:

**Comment by wasamasa** [comment]
Now that I'm actually writing error handling for my bindings, I have a clearer idea what steps would be needed for handling this properly:

- Remove debug printing
- Offer functions for retrieving a message on an error condition, ideally by just wrapping `IMG_GetError` and `TTF_GetError`
- Document how one fetches errors, add it to the examples
