### ISSUE TITLE
Splitting up KW_Paint into KW_ProcessEvents and KW_Paint

### ISSUE THREAD

**Issue by wasamasa** [mobius3/KiWi#9]
Today I've dealt with the callback side of this library and found out that for my bindings to execute Scheme callbacks correctly, I must declare `KW_Paint` as a safe function.  This is apparently because `KW_Paint` handles both event processing and painting, unlike what its name suggests.  A possible fix is documenting `KW_ProcessEvents` in `KW_gui.h`, removing its function call from `KW_Paint`, then updating all examples to use `KW_ProcessEvents` before `KW_Paint`.

**Comment by mobius3** [comment]
This was in my radar before. Thanks for bringing it up. I hope it is more suitable for your bindings now.

**Comment by wasamasa** [comment]
Thanks, I've updated them accordingly.
